[package]
name = "hw12"
version = "1.0.0"
authors = []

[addresses]
hw12 = "0x968135178e36d51df8007542c3e9bb277f7db6b140679b9226a9e408d050f661"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token-objects"


[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token"